[Generale]
fqdn_sito="lilbib.example.org"
porta_http=":8080"
lunghezza_pagina=25
utente_admin="admin"
chiave_firma="secret"
dummy_auth=false

[LDAP]
host="ldap.example.org"
porta="389"

[SQL]
username="lilbib"
password="secret"
indirizzo="localhost"
database="lilbib"
