[Generale]
#fqdn_sito="lilbib.example.org"
fqdn_sito="localhost"
porta_http=":8080"
lunghezza_pagina=24
utente_admin="admin"
chiave_firma="secret"
#cookie_sicuri=true
cookie_sicuri=false
#dummy_auth=false
dummy_auth=true

[LDAP]
host="ldap.example.org"
porta="389"

[SQL]
username="lilbib"
password="secret"
indirizzo="localhost"
database="lilbib"
