[Generale]
admin="admin"
chiave_firma="secret"
fqdn_sito="lilbib.example.org"
dummy_auth=false

[LDAP]
host="ldap.example.org"
porta="389"

[SQL]
username="lilbib"
password="secret"
indirizzo="localhost"
database="lilbib"
