[Generale]
fqdn_sito="localhost"
porta_http=":8080"
lunghezza_pagina=24
utente_admin="admin"

[Autenticazione]
chiave_firma="secret"
usa_sso=false
sso_url="https://sso.example.org"
cookie_sicuri=false
dummy_auth=true

[LDAP]
host="ldap.example.org"
porta="389"
utente="admin"
password="admin"
base_dn="dc=example,dc=org"

[SQL]
username="lilbib"
password="secret"
indirizzo="localhost"
database="lilbib"
