[Generale]
#fqdn_sito="lilbib.example.org"
fqdn_sito="localhost"
porta_http=":8080"
lunghezza_pagina=24
utente_admin="admin"

[Autenticazione]
chiave_firma="secret"
usa_sso=false
sso_url="https://sso.example.org"
cookie_sicuri=false
#cookie_sicuri=true
dummy_auth=true
#dummy_auth=false

[LDAP]
host="ldap.example.org"
porta="389"

[SQL]
username="lilbib"
password="secret"
indirizzo="localhost"
database="lilbib"
