[Generale]
admin="admin"
chiave_firma="secret"
fqdn_sito="example.org"
dummy_auth=true

[LDAP]
host="ldap.example.org"
porta="389"

[SQL]
username="asdf"
password="asdf"
indirizzo="asdf"
database="asdf"
